# Generated by Django 4.2.1 on 2024-06-09 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.city'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.city'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='company_position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dealership.companyposition'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='office',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dealership.office'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.city'),
        ),
    ]
