apiVersion: v1
kind: Pod
metadata:
  name: db-dealership
  labels:
    app: db-dealership
spec:
  containers:
    - name: db-dealership
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
      - name: DATABASE_HOST
        value: postgres
      - name: POSTGRES_DB
        value: msvc_dealership
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: db-dealership
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: dealership
