apiVersion: v1
kind: Pod
metadata:
  name: dealership
  labels:
    app: dealership
spec:
  containers:
    - name: dealership
      image: marcelounivalle/msvc_dealership:1.0.2
      ports:
        - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: dealership
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  selector:
    app: dealership
